version: '3.8'

services:
  # Storage Nodes (LSMTree)
  storage-node-1:
    build: .
    container_name: lsmtree-node-1
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CLUSTER_NODE_ID=node-1
      - CLUSTER_NODE_HOST=storage-node-1
      - CLUSTER_NODE_PORT=8080
    volumes:
      - lsmtree-data-1:/app/data
      - lsmtree-logs-1:/app/logs
    networks:
      - lsmtree-network

  storage-node-2:
    build: .
    container_name: lsmtree-node-2
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CLUSTER_NODE_ID=node-2
      - CLUSTER_NODE_HOST=storage-node-2
      - CLUSTER_NODE_PORT=8080
    volumes:
      - lsmtree-data-2:/app/data
      - lsmtree-logs-2:/app/logs
    networks:
      - lsmtree-network

  storage-node-3:
    build: .
    container_name: lsmtree-node-3
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CLUSTER_NODE_ID=node-3
      - CLUSTER_NODE_HOST=storage-node-3
      - CLUSTER_NODE_PORT=8080
    volumes:
      - lsmtree-data-3:/app/data
      - lsmtree-logs-3:/app/logs
    networks:
      - lsmtree-network

  # Source Coordinator
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: source-coordinator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - coordinator-data:/app/coordinator-data
      - coordinator-logs:/app/logs
    depends_on:
      - storage-node-1
      - storage-node-2
      - storage-node-3
    networks:
      - lsmtree-network

volumes:
  lsmtree-data-1:
  lsmtree-data-2:
  lsmtree-data-3:
  lsmtree-logs-1:
  lsmtree-logs-2:
  lsmtree-logs-3:
  coordinator-data:
  coordinator-logs:

networks:
  lsmtree-network:
    driver: bridge 