# LSM Tree Timeseries Storage Configuration

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: lsmtree-timeseries
  profiles:
    active: dev

# LSM Tree Configuration
lsm:
  # MemTable settings
  memtable:
    max-size-mb: 64
    max-points: 100000
    flush-threshold: 0.8
  sstable:
    max-size-mb: 256
    merge-threshold: 10
  
  # Write-Ahead Log settings
  wal:
    enabled: true
    sync-on-write: true
  
  # Storage settings
  storage:
    directory: ./data
  
  # Compaction settings
  compaction:
    interval-seconds: 300
    max-l0-tables: 4
    level-size-multiplier: 10
    max-concurrent-compactions: 2
  
  # Bloom filter settings
  bloom-filter:
    enabled: true
    false-positive-rate: 0.01

# Cluster Configuration
cluster:
  node:
    id: "node-1"
    host: "localhost"
    port: 8080
  discovery:
    enabled: true
    initial-nodes: []
  heartbeat:
    interval-ms: 100
    timeout-ms: 5000
  election:
    timeout-ms: 1000
    max-timeout-ms: 2000

# Replication Configuration
replication:
  write-consistency: QUORUM
  read-consistency: ONE
  replication-timeout-ms: 5000
  max-retries: 3
  async-replication: false
  max-replication-lag-ms: 10000
  replication-lag-check-interval-ms: 1000
  auto-failover: true
  failover-timeout-ms: 30000

# Sharding Configuration
sharding:
  num-shards: 16
  replication-factor: 3
  health-check-interval-ms: 5000

# Logging configuration
logging:
  level:
    com.lsmtree: INFO
    com.lsmtree.cluster: DEBUG
    com.lsmtree.replication: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/lsm-timeseries.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,stats
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Coordinator Configuration
coordinator:
  healthcheck:
    interval-ms: 5000
  storage:
    directory: ./coordinator-data

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

lsm:
  memtable:
    max-size-mb: 32
    max-points: 50000
  compaction:
    interval-seconds: 60

logging:
  level:
    com.lsmtree: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

lsm:
  memtable:
    max-size-mb: 128
    max-points: 200000
  compaction:
    interval-seconds: 600

logging:
  level:
    com.lsmtree: WARN
    root: WARN 